name: safecty
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.18.1
  json_class: ^3.0.0+8
  jwt_decoder: ^2.0.1
  logging: ^1.0.2
  lottie: ^2.7.0
  package_info_plus: ^5.0.1
  path: ^1.8.0
  path_provider: ^2.0.9
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  provider: ^6.0.2
  sembast: ^3.2.0
  signature: ^5.4.1
  simple_animation_transition: ^0.0.6
  simple_animations: ^5.0.2
  syncfusion_flutter_charts: ^23.2.7
  url_launcher: ^6.1.5
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/config/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

flutter_intl:
  class_name: AppLocalizations
  enabled: true
  main_locale: es_CO

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash12.png
    icon_background_color: "#ffffff"

  android: true
  ios: true
  web: false
